// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ7qxme1BblRNE1TnExYZJ6zr2bEpi0zo',
    appId: '1:997814723101:web:22dbf65eed200164a69cf4',
    messagingSenderId: '997814723101',
    projectId: 'to-allah',
    authDomain: 'to-allah.firebaseapp.com',
    storageBucket: 'to-allah.appspot.com',
    measurementId: 'G-K8GSE0FEYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB39TQO0w5WhnKjRii41n9btBvOe6EY_6Q',
    appId: '1:997814723101:android:fb04a24384e0cc93a69cf4',
    messagingSenderId: '997814723101',
    projectId: 'to-allah',
    storageBucket: 'to-allah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB92eraM4QNqNDmlbpebq7cci3J4c78w6w',
    appId: '1:997814723101:ios:88b8380f195623f0a69cf4',
    messagingSenderId: '997814723101',
    projectId: 'to-allah',
    storageBucket: 'to-allah.appspot.com',
    iosBundleId: 'com.example.toAllah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB92eraM4QNqNDmlbpebq7cci3J4c78w6w',
    appId: '1:997814723101:ios:3f71dca5076ea07ca69cf4',
    messagingSenderId: '997814723101',
    projectId: 'to-allah',
    storageBucket: 'to-allah.appspot.com',
    iosBundleId: 'com.example.toAllah.RunnerTests',
  );
}
